In [21]:
import pandas as pd


df = pd.read_csv('data.csv', sep = '\t')
df

       y  const    x1    x2     x3    x4    x5
0    9.7      1  1.59  0.26   2.05  0.32  0.14
1    8.4      1  0.34  0.28   0.46  0.59  0.66
2    9.0      1  2.53  0.31   2.46  0.30  0.31
3    9.9      1  4.63  0.40   6.44  0.43  0.59
4    9.6      1  2.16  0.26   2.16  0.39  0.16
5    8.6      1  2.16  0.30   2.69  0.32  0.17
6   12.5      1  0.68  0.10   0.73  0.42  0.23
7    7.6      1  0.35  0.26   0.42  0.21  0.08
8    6.8      1  0.52  0.24   0.49  0.20  0.08
9   13.5      1  3.42  0.31   3.02  1.37  0.80
10   9.7      1  1.78  0.30   3.19  0.73  0.17
11  10.7      1  2.40  0.32   3.30  0.25  0.14
12  12.1      1  9.36  0.40  11.00  0.39  0.38
13   9.7      1  1.72  0.28   2.26  0.82  0.17
14   7.1      1  0.59  0.29   0.60  0.13  0.35
15   7.2      1  0.28  0.26   0.30  0.09  0.15
16   8.2      1  1.64  0.25   1.44  0.20  0.08
17   8.4      1  0.09  0.22   0.05  0.43  0.20
18  13.1      1  0.08  0.25   0.03  0.73  0.20
19   8.7      1  1.36  0.26   1.23  0.99  0.42

In [22]:
import numpy as np



X = df.drop(columns = ['y'])
y = df['y']

mnk_beta = np.linalg.inv(X.T @ X)  @ X.T @ y
mnk_beta

0    11.654960
1     0.070894
2   -18.382913
3     0.547547
4     3.344459
5     0.246444
dtype: float64

In [ ]:

a = 0.1
ridge_beta = np.linalg.inv(X.T @ X + a * np.eye((X.T @ X).shape[0])) @ X.T @ y




ridge_beta

0    7.954032
1    0.414044
2   -2.689217
3    0.019948
4    3.543652
5   -0.716713
dtype: float64

In [ ]:
from sklearn.linear_model import Lasso

from sklearn.model_selection import train_test_split

# suppress=True убирает 1e-05, precision=4 задает 4 знака после запятой
np.set_printoptions(suppress=True, precision=4)




lasso = Lasso(alpha= 0.1)
lasso.fit(df.drop(columns = ['y']), df['y'])
pd.DataFrame(lasso.coef_)

          0
0  0.000000
1  0.338592
2 -0.000000
3  0.000000
4  2.277575
5  0.000000

В исходной модели МНК коэффициенты сильно искажены из-за мультиколлинеарности: признаки x1, x2 и x3 тесно связаны между собой (корреляция между x1 и x3 достигает 0.98). В результате дисперсия оценок раздулась, а коэффициент при x2 получил неадекватное и контринтуитивное значение −18.38, из-за чего классический МНК нельзя корректно интерпретировать.

Ridge-регуляризация (L2) решила проблему раздутых весов за счет их стягивания к нулю. Оценка при x2 сократилась с −18.38 до приемлемых −2.69, сохранив при этом все признаки в модели и сделав ее устойчивой к шуму.

Lasso-регуляризация (L1) пошла дальше и выполнила автоматический отбор признаков. Она полностью занулила избыточные и дублирующие факторы (x2, x3, x5). В итоговой модели остались только два ключевых фактора: x4 (коэффициент около 2.28) и x1 (коэффициент около 0.34), которые вносят основной положительный вклад в целевую переменную y.